/**
 * Aervox｜思隅 @aervox/worker — 日记生成 Worker
 *
 * 规则依据：PRD §8（DiarySchedule/DiaryCycle/DiaryVersion）+ ADR-011。
 *
 * 骨架：跨租户扫描到期 schedule → 创建不可变周期 → 汇总窗口素材 → 发布日记版本 + Outbox 事件。
 * 实际模型生成尚未接入（占位内容），后续在 publish 前插入模型调用即可，不改变周期/版本事务边界。
 */
import { and, eq, lte, sql } from "drizzle-orm";
import {
  diarySchedules,
  diaryMaterialBuffers,
  type AervoxDatabase,
  type SqliteDiaryRepository,
  type SqlitePlatformRepository,
  type SqliteOutboxRepository,
  type TenantContext,
} from "@aervox/database";

export interface DiaryGeneratorContext {
  db: AervoxDatabase;
  diaryRepo: SqliteDiaryRepository;
  platformRepo: SqlitePlatformRepository;
  outboxRepo: SqliteOutboxRepository;
  workerId: string;
}

let seq = 0;
const id = (prefix: string): string =>
  `${prefix}_${Date.now().toString(36)}_${(++seq).toString(36)}`;

const toLocalDate = (iso: string): string => iso.slice(0, 10);

/** 单次日记生成扫描；返回生成的日记数量 */
export async function runDiaryGenerationCycle(ctx: DiaryGeneratorContext): Promise<number> {
  const now = new Date().toISOString();

  // 跨租户只读：扫描到期且启用的计划
  const schedules = await ctx.db
    .select()
    .from(diarySchedules)
    .where(
      and(
        eq(diarySchedules.enabled, 1),
        sql`(${diarySchedules.nextRunAt} IS NULL OR ${diarySchedules.nextRunAt} <= ${now})`,
      ),
    )
    .limit(20);

  let generated = 0;
  for (const schedule of schedules) {
    const tenant: TenantContext = {
      workspaceId: schedule.workspaceId,
      subjectUserId: schedule.subjectUserId,
    };
    const localDate = toLocalDate(schedule.nextRunAt ?? now);

    try {
      // 1. 创建不可变周期（scheduleVersion=1）
      const cycle = await ctx.diaryRepo.createCycle(tenant, {
        id: id("cyc"),
        scheduleEpochId: schedule.scheduleEpochId,
        localDate,
        previousCutoffAt: schedule.lastCutoffAt ?? schedule.activeFrom,
        cutoffAt: now,
      });

      // 2. 汇总该窗口素材（跨租户只读，按租户 + occurredAt 窗口归属，非新 cycleId）
      const materials = await ctx.db
        .select({ sourceRevisionId: diaryMaterialBuffers.sourceRevisionId })
        .from(diaryMaterialBuffers)
        .where(
          and(
            eq(diaryMaterialBuffers.workspaceId, tenant.workspaceId),
            eq(diaryMaterialBuffers.subjectUserId, tenant.subjectUserId),
            eq(diaryMaterialBuffers.status, "buffered"),
            sql`${diaryMaterialBuffers.occurredAt} >= ${cycle.previousCutoffAt}`,
            sql`${diaryMaterialBuffers.occurredAt} <= ${cycle.cutoffAt}`,
          ),
        )
        .limit(50);
      const materialCount = materials.length;

      // 3. 生成日记（骨架占位内容；接入模型后替换此步）
      const content =
        materialCount > 0
          ? `今日从 ${materialCount} 份素材中生成。${materials.map((m) => m.sourceRevisionId).join("、")}`
          : "今日暂无可回素材，记录了当前学习状态。";

      // 4. 同一事务发布日记 + 周期状态 + Outbox + 创建日记版本
      const published = await ctx.diaryRepo.publishDiaryWithCycle(tenant, {
        cycleId: cycle.id,
        diary: {
          id: id("diary"),
          localDate,
          title: `日记 ${localDate}`,
          content,
          autoGenerated: 1,
        },
        expectedScheduleVersion: 1,
        outboxEvent: {
          id: id("outbox"),
          eventType: "diary.published",
          idempotencyKey: id("idem_diary"),
          payload: { cycleId: cycle.id, localDate },
        },
      });
      await ctx.diaryRepo.createDiaryVersion(tenant, {
        id: id("dv"),
        diaryId: published.diary.id,
        perspective: "ai_generated",
        content,
      });

      // 5. 推进计划游标（+1 天；自定义 cron 后续按 cutoffRule 计算）
      const nextRun = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
      await ctx.db
        .update(diarySchedules)
        .set({ nextRunAt: nextRun, lastCutoffAt: now, updatedAt: now })
        .where(eq(diarySchedules.id, schedule.id));

      await ctx.platformRepo.createAuditRecord(tenant, {
        id: id("aud"),
        actorType: "system",
        actorId: `diary:${ctx.workerId}`,
        action: "diary.generated",
        subjectType: "diary_cycle",
        subjectId: cycle.id,
        metadata: { localDate, materialCount },
      });
      generated += 1;
    } catch (err) {
      console.error(`[diary-generator] schedule ${schedule.id} failed:`, err);
    }
  }
  return generated;
}
