import { createSqliteDiaryMaterialPort } from "@aervox/repositories";
import { loadLoopProvider } from "@aervox/config";
/**
 * Aervox｜思隅 @aervox/worker — 日记生成 Worker（定时兜底路径）
 *
 * 规则依据：PRD §8（DiarySchedule/DiaryCycle/DiaryVersion）+ ADR-011。
 *
 * 与按需路径（对话工具 / POST generate-today）共用 @aervox/diary 生成单源：
 * - 素材 = 当日消息 + 当日记忆 + 学习目标 + 当日练习（collectDiaryMaterial）；
 * - AI 依据当天记忆与上下文、模仿人类写日记（Prompt/模板降级均在共享服务内）；
 * - 同日已存在日记则跳过（推进游标），避免与按需路径对同日唯一索引的冲突；
 * - localDate 统一服务器本地日期（localDateToday），修正既定 UTC 前缀偏差。
 */
import type {
  AervoxDatabase,
  SqliteDiaryRepository,
  SqliteLLMConfigRepository,
  SqlitePlatformRepository,
  SqliteOutboxRepository,
  LocalContext,
} from "@aervox/repositories";
import {
  createLlmDiaryModelPort,
  createRepoDiaryLlmConfigPort,
  DiaryGenerationService,
  generateDiaryId,
  localDateToday,
} from "@aervox/diary";

export interface DiaryGeneratorContext {
  db: AervoxDatabase;
  diaryRepo: SqliteDiaryRepository;
  llmConfigRepo: SqliteLLMConfigRepository;
  platformRepo: SqlitePlatformRepository;
  outboxRepo: SqliteOutboxRepository;
  workerId: string;
}

const DAY_MS = 24 * 60 * 60 * 1000;

/** 单次日记生成扫描；返回生成的日记数量 */
export async function runDiaryGenerationCycle(ctx: DiaryGeneratorContext): Promise<number> {
  const now = new Date().toISOString();

  const schedules = await ctx.diaryRepo.listDueSchedules(now);

  if (schedules.length === 0) return 0;

  const generation = new DiaryGenerationService({
    materials: createSqliteDiaryMaterialPort(ctx.db),
    useModel: loadLoopProvider() === "llm",
    model: createLlmDiaryModelPort(createRepoDiaryLlmConfigPort(ctx.llmConfigRepo)),
  });

  let generated = 0;
  for (const schedule of schedules) {
    const tenant: LocalContext = { workspaceId: "local", subjectUserId: "local" };
    // 服务器本地日期（与按需路径同一日期语义，避免同日错位）
    const localDate = localDateToday(new Date());

    try {
      // 0. 同日已存在（按需路径可能已生成）→ 跳过并推进游标，避免唯一索引冲突
      const existingDiary = await ctx.diaryRepo.getDiaryByDate(tenant, localDate);
      if (existingDiary) {
        await ctx.diaryRepo.advanceSchedule(schedule.id, new Date(Date.now() + DAY_MS).toISOString(), now);
        continue;
      }

      // 1. 创建不可变周期（scheduleVersion=1）
      const cycle = await ctx.diaryRepo.createCycle(tenant, {
        id: generateDiaryId("cyc"),
        scheduleEpochId: schedule.scheduleEpochId,
        localDate,
        previousCutoffAt: schedule.lastCutoffAt ?? schedule.activeFrom,
        cutoffAt: now,
      });

      // 2. 生成日记（LLM 或模板降级，均在共享服务内决策；素材采集与计数由端口统一）
      const window = { startIso: cycle.previousCutoffAt, endIso: cycle.cutoffAt };
      const draft = await generation.generate(tenant, { localDate, window });

      // 3. 同一事务发布日记 + 周期状态 + Outbox + 创建日记版本
      await ctx.diaryRepo.publishDiaryWithCycle(tenant, {
        cycleId: cycle.id,
        diary: {
          id: generateDiaryId("diary"),
          localDate,
          title: draft.title,
          content: draft.content,
          autoGenerated: 1,
        },
        expectedScheduleVersion: 1,
        version: { id: generateDiaryId("dv"), perspective: "ai_generated" },
        advance: { scheduleId: schedule.id, nextRunAt: new Date(Date.now() + DAY_MS).toISOString(), lastCutoffAt: now },
        outboxEvent: {
          id: generateDiaryId("outbox"),
          eventType: "diary.published",
          idempotencyKey: generateDiaryId("idem_diary"),
          payload: { cycleId: cycle.id, localDate },
        },
      });
      await ctx.platformRepo.createAuditRecord(tenant, {
        id: generateDiaryId("aud"),
        actorType: "system",
        actorId: `diary:${ctx.workerId}`,
        action: "diary.generated",
        subjectType: "diary_cycle",
        subjectId: cycle.id,
        metadata: { localDate, materialCount: draft.materialCount, generatedBy: draft.generatedBy },
      });
      generated += 1;
    } catch (err) {
      console.error(`[diary-generator] schedule ${schedule.id} failed:`, err);
    }
  }
  return generated;
}
