/**
 * Aervox｜思隅 @aervox/database — 日记与不可变调度周期实体表
 *
 * 规则依据：docs/architecture/adr/ADR-011-diary-cycle-schedule-revision.md
 */
import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenantColumns, timestampColumns } from "./common.js";

/** 日记主表 */
export const diaries = sqliteTable(
  "diaries",
  {
    id: text("id").primaryKey(),
    ...tenantColumns,
    localDate: text("local_date").notNull(), // YYYY-MM-DD 日期标签
    autoGenerated: integer("auto_generated").notNull().default(1),
    title: text("title").notNull(),
    content: text("content").notNull(),
    version: integer("version").notNull().default(1),
    ...timestampColumns,
  },
  (table) => ({
    // SQLite 条件唯一索引：同一日期标签仅限一份 autoGenerated=1 的自动日记
    autoDiaryUniqueIdx: uniqueIndex("diaries_auto_unique_idx")
      .on(table.workspaceId, table.subjectUserId, table.localDate)
      .where(sql`${table.autoGenerated} = 1`),
  }),
);

/** 日记周期不可变窗口表（DiaryCycle） */
export const diaryCycles = sqliteTable(
  "diary_cycles",
  {
    id: text("id").primaryKey(),
    ...tenantColumns,
    scheduleEpochId: text("schedule_epoch_id").notNull(),
    localDate: text("local_date").notNull(),
    previousCutoffAt: text("previous_cutoff_at").notNull(),
    cutoffAt: text("cutoff_at").notNull(),
    status: text("status").notNull().default("Scheduled"), // Scheduled, Claimed, Generating, Validating, Published, Skipped, Failed, Cancelled
    scheduleVersion: integer("schedule_version").notNull().default(1),
    fencingToken: integer("fencing_token").notNull().default(0),
    diaryId: text("diary_id"),
    ...timestampColumns,
  },
  (table) => ({
    tenantCycleIdx: index("diary_cycles_tenant_idx").on(
      table.workspaceId,
      table.subjectUserId,
      table.cutoffAt,
    ),
  }),
);

/** 日记计划不可变修订表 */
export const diaryScheduleRevisions = sqliteTable(
  "diary_schedule_revisions",
  {
    id: text("id").primaryKey(),
    ...tenantColumns,
    revision: integer("revision").notNull(),
    enabled: integer("enabled").notNull().default(1),
    cronTime: text("cron_time").notNull(),
    timezone: text("timezone").notNull(),
    initialWindowStart: text("initial_window_start").notNull(),
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    tenantRevIdx: uniqueIndex("diary_schedule_rev_idx").on(
      table.workspaceId,
      table.subjectUserId,
      table.revision,
    ),
  }),
);

/** 日记生成尝试表（带 lease 过期时间） */
export const diaryRunAttempts = sqliteTable(
  "diary_run_attempts",
  {
    id: text("id").primaryKey(),
    cycleId: text("cycle_id")
      .notNull()
      .references(() => diaryCycles.id, { onDelete: "cascade" }),
    scheduleVersion: integer("schedule_version").notNull(),
    workerId: text("worker_id").notNull(),
    attempt: integer("attempt").notNull().default(1),
    status: text("status").notNull(),
    leaseExpiresAt: text("lease_expires_at").notNull(),
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    cycleAttemptIdx: index("diary_attempts_cycle_idx").on(table.cycleId, table.attempt),
  }),
);
