/**
 * Aervox｜思隅 @aervox/repositories — diary 仓储类型（自 types.ts 机械拆分）
 */
import type { DiaryCycleModel, DiaryModel } from "./memory-embedding.js";
import type { LocalContext } from "../../local-context.js";

export interface IDiaryRepository {
  createCycle(
    ctx: LocalContext,
    cycle: {
      id: string;
      scheduleEpochId: string;
      localDate: string;
      previousCutoffAt: string;
      cutoffAt: string;
      status?: string;
    },
  ): Promise<DiaryCycleModel>;
  getCycle(ctx: LocalContext, cycleId: string): Promise<DiaryCycleModel | null>;
  claimCycleWithLease(
    ctx: LocalContext,
    params: {
      cycleId: string;
      workerId: string;
      leaseDurationMs: number;
      expectedScheduleVersion: number;
    },
  ): Promise<{ success: boolean; newScheduleVersion?: number; fencingToken?: number }>;
  publishDiaryWithCycle(
    ctx: LocalContext,
    params: {
      cycleId: string;
      diary: { id: string; localDate: string; title: string; content: string; autoGenerated?: number };
      expectedScheduleVersion: number;
      outboxEvent?: { id: string; eventType: string; idempotencyKey: string; payload: unknown };
    },
  ): Promise<{ diary: DiaryModel; cycle: DiaryCycleModel }>;
  getDiaryByDate(ctx: LocalContext, localDate: string): Promise<DiaryModel | null>;
  /** 历史回看：按日期倒序返回最近 limit 篇日记 */
  listDiaries(ctx: LocalContext, limit: number): Promise<DiaryModel[]>;
  // MVP+ 补齐（PRD §8）：计划主实体 / 版本 / 段落来源 / 素材缓冲
  createDiarySchedule(
    ctx: LocalContext,
    schedule: {
      id: string;
      scheduleEpochId: string;
      activeFrom: string;
      initialWindowStart: string;
      cutoffRule: string;
      bufferMinutes?: number;
      contentScopes?: unknown;
      quietHours?: unknown;
      enabled?: number;
      nextRunAt?: string;
    },
  ): Promise<DiaryScheduleModel>;
  getDiarySchedule(ctx: LocalContext, id: string): Promise<DiaryScheduleModel | null>;
  /** 默认每日计划幂等查询：返回该租户首个启用且 cutoffRule=daily 的计划（无返回 null） */
  getActiveDailySchedule(ctx: LocalContext): Promise<DiaryScheduleModel | null>;
  createDiaryVersion(
    ctx: LocalContext,
    version: { id: string; diaryId: string; perspective: string; content: string; modelRunId?: string | null },
  ): Promise<DiaryVersionModel>;
  /** 改写路径：主行内容推进到新版本（version+1、状态转 edited；历史版本不覆盖） */
  updateDiaryContent(
    ctx: LocalContext,
    diaryId: string,
    update: { title?: string; content: string },
  ): Promise<DiaryModel>;
  createDiaryParagraphSource(
    source: {
      id: string;
      diaryVersionId: string;
      paragraphIndex: number;
      sourceArtifactId: string;
      sourceRevisionId: string;
      permissionSnapshot?: unknown;
    },
  ): Promise<DiaryParagraphSourceModel>;
  createDiaryMaterialBuffer(
    ctx: LocalContext,
    buffer: {
      id: string;
      cycleId: string;
      sourceArtifactId: string;
      sourceRevisionId: string;
      occurredAt: string;
      ingestedAt: string;
      expiresAt: string;
      ephemeralSnapshot?: unknown;
      permissionSnapshot?: unknown;
    },
  ): Promise<DiaryMaterialBufferModel>;
}

export interface DiaryScheduleModel {
  id: string;
  enabled: number;
  scheduleEpochId: string;
  activeFrom: string;
  disabledAt?: string | null;
  currentRevisionId?: string | null;
  nextRunAt?: string | null;
  lastCutoffAt?: string | null;
  initialWindowStart: string;
  cutoffRule: string;
  bufferMinutes: number;
  contentScopes?: unknown;
  quietHours?: unknown;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface DiaryVersionModel {
  id: string;
  diaryId: string;
  perspective: string;
  content: string;
  modelRunId?: string | null;
  createdAt: string;
  supersededAt?: string | null;
}

export interface DiaryParagraphSourceModel {
  id: string;
  diaryVersionId: string;
  paragraphIndex: number;
  sourceArtifactId: string;
  sourceRevisionId: string;
  permissionSnapshot?: unknown;
}

export interface DiaryMaterialBufferModel {
  id: string;
  cycleId: string;
  sourceArtifactId: string;
  sourceRevisionId: string;
  occurredAt: string;
  ingestedAt: string;
  ephemeralSnapshot?: unknown;
  permissionSnapshot?: unknown;
  expiresAt: string;
  status: string;
}
