/**
 * Aervox｜思隅 @aervox/repositories — memory-embedding 仓储类型（自 types.ts 机械拆分）
 */
import type { MemoryEmbeddingBatchProgress } from "./memory-compaction.js";
import type { LocalContext } from "../../local-context.js";

export interface IMemoryEmbeddingRepository {
  /**
   * 批量写入向量（对照 AST-02 Port 形态：分批 + 重试 + 进度回调）。
   * 同一 memoryId 已有向量时覆盖（同 model_id 重算场景），换模型请用不同 model_id。
   */
  insertBatch(
    tenant: LocalContext,
    items: Array<{
      id: string;
      memoryId: string;
      vector: number[];
      modelId: string;
      sourceCreatedAt?: string | null;
      indexVersion?: number;
    }>,
    options?: {
      batchSize?: number;
      maxRetries?: number;
      progressCallback?: (progress: MemoryEmbeddingBatchProgress) => void;
    },
  ): Promise<void>;
  /** 余弦检索 topK（JS 行扫描，SQLite 无原生向量扩展时的兜底） */
  retrieve(
    tenant: LocalContext,
    queryVector: number[],
    topK: number,
    minScore?: number,
    modelId?: string,
  ): Promise<Array<{ memoryId: string; score: number }>>;
  deleteByMemoryId(tenant: LocalContext, memoryId: string): Promise<void>;
  clearTenant(tenant: LocalContext): Promise<void>;
}

export interface DiaryModel {
  id: string;
  workspaceId?: string;
  subjectUserId?: string;
  localDate: string;
  autoGenerated: number;
  title: string;
  content: string;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface DiaryCycleModel {
  id: string;
  workspaceId?: string;
  subjectUserId?: string;
  scheduleEpochId: string;
  localDate: string;
  previousCutoffAt: string;
  cutoffAt: string;
  status: string;
  scheduleVersion: number;
  fencingToken: number;
  diaryId?: string | null;
  createdAt: string;
  updatedAt: string;
}
