/**
 * Aervox｜思隅 @aervox/database — 日记与调度周期 SQLite 仓储实现
 *
 * 规则依据：ADR-011 不可变周期、计划修订、CAS 乐观锁与 lease/fencing
 */
import { eq, and, sql } from "drizzle-orm";
import type { AervoxDatabase } from "../../client.js";
import { diaries, diaryCycles, diaryRunAttempts, outboxEvents } from "../../schema/index.js";
import { assertTenantContext, type TenantContext } from "../../tenant.js";
import type {
  IDiaryRepository,
  DiaryModel,
  DiaryCycleModel,
} from "../types.js";

export class SqliteDiaryRepository implements IDiaryRepository {
  constructor(private readonly db: AervoxDatabase) {}

  async createCycle(
    tenant: TenantContext,
    cycleData: {
      id: string;
      scheduleEpochId: string;
      localDate: string;
      previousCutoffAt: string;
      cutoffAt: string;
      status?: string;
    },
  ): Promise<DiaryCycleModel> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();
    const [created] = await this.db
      .insert(diaryCycles)
      .values({
        id: cycleData.id,
        workspaceId: tenant.workspaceId,
        subjectUserId: tenant.subjectUserId,
        scheduleEpochId: cycleData.scheduleEpochId,
        localDate: cycleData.localDate,
        previousCutoffAt: cycleData.previousCutoffAt,
        cutoffAt: cycleData.cutoffAt,
        status: cycleData.status ?? "Scheduled",
        scheduleVersion: 1,
        fencingToken: 0,
        createdAt: now,
        updatedAt: now,
      })
      .returning();
    return created as DiaryCycleModel;
  }

  async getCycle(tenant: TenantContext, cycleId: string): Promise<DiaryCycleModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diaryCycles)
      .where(
        and(
          eq(diaryCycles.id, cycleId),
          eq(diaryCycles.workspaceId, tenant.workspaceId),
          eq(diaryCycles.subjectUserId, tenant.subjectUserId),
        ),
      );
    return (found as DiaryCycleModel) ?? null;
  }

  async claimCycleWithLease(
    tenant: TenantContext,
    params: {
      cycleId: string;
      workerId: string;
      leaseDurationMs: number;
      expectedScheduleVersion: number;
    },
  ): Promise<{ success: boolean; newScheduleVersion?: number; fencingToken?: number }> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();
    const leaseExpiresAt = new Date(Date.now() + params.leaseDurationMs).toISOString();

    return await this.db.transaction(async (tx) => {
      // 执行 CAS 乐观锁更新 scheduleVersion
      const [updated] = await tx
        .update(diaryCycles)
        .set({
          status: "Claimed",
          scheduleVersion: sql`${diaryCycles.scheduleVersion} + 1`,
          fencingToken: sql`${diaryCycles.fencingToken} + 1`,
          updatedAt: now,
        })
        .where(
          and(
            eq(diaryCycles.id, params.cycleId),
            eq(diaryCycles.workspaceId, tenant.workspaceId),
            eq(diaryCycles.subjectUserId, tenant.subjectUserId),
            eq(diaryCycles.scheduleVersion, params.expectedScheduleVersion),
          ),
        )
        .returning();

      if (!updated) {
        return { success: false };
      }

      // 记录 Worker 执行尝试
      const attemptId = `att_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
      await tx.insert(diaryRunAttempts).values({
        id: attemptId,
        cycleId: params.cycleId,
        scheduleVersion: updated.scheduleVersion,
        workerId: params.workerId,
        attempt: updated.fencingToken,
        status: "Claimed",
        leaseExpiresAt,
        createdAt: now,
      });

      return {
        success: true,
        newScheduleVersion: updated.scheduleVersion,
        fencingToken: updated.fencingToken,
      };
    });
  }

  async publishDiaryWithCycle(
    tenant: TenantContext,
    params: {
      cycleId: string;
      diary: { id: string; localDate: string; title: string; content: string; autoGenerated?: number };
      expectedScheduleVersion: number;
      outboxEvent?: { id: string; eventType: string; idempotencyKey: string; payload: unknown };
    },
  ): Promise<{ diary: DiaryModel; cycle: DiaryCycleModel }> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();

    return await this.db.transaction(async (tx) => {
      // 1. 插入日记实体（SQLite 条件唯一索引防护重复自动日记）
      const [createdDiary] = await tx
        .insert(diaries)
        .values({
          id: params.diary.id,
          workspaceId: tenant.workspaceId,
          subjectUserId: tenant.subjectUserId,
          localDate: params.diary.localDate,
          autoGenerated: params.diary.autoGenerated ?? 1,
          title: params.diary.title,
          content: params.diary.content,
          version: 1,
          createdAt: now,
          updatedAt: now,
        })
        .returning();

      if (!createdDiary) {
        throw new Error("Failed to insert diary record");
      }

      // 2. CAS 更新周期状态为 Published 并绑定 diaryId
      const [updatedCycle] = await tx
        .update(diaryCycles)
        .set({
          status: "Published",
          diaryId: createdDiary.id,
          scheduleVersion: sql`${diaryCycles.scheduleVersion} + 1`,
          updatedAt: now,
        })
        .where(
          and(
            eq(diaryCycles.id, params.cycleId),
            eq(diaryCycles.workspaceId, tenant.workspaceId),
            eq(diaryCycles.subjectUserId, tenant.subjectUserId),
            eq(diaryCycles.scheduleVersion, params.expectedScheduleVersion),
          ),
        )
        .returning();

      if (!updatedCycle) {
        throw new Error(
          `Failed to publish diary: cycle ${params.cycleId} version mismatch (expected ${params.expectedScheduleVersion})`,
        );
      }

      // 3. 在同一事务写入 Outbox
      if (params.outboxEvent) {
        await tx.insert(outboxEvents).values({
          id: params.outboxEvent.id,
          workspaceId: tenant.workspaceId,
          subjectUserId: tenant.subjectUserId,
          idempotencyKey: params.outboxEvent.idempotencyKey,
          eventType: params.outboxEvent.eventType,
          payload: params.outboxEvent.payload,
          status: "pending",
          createdAt: now,
        });
      }

      return {
        diary: createdDiary as DiaryModel,
        cycle: updatedCycle as DiaryCycleModel,
      };
    });
  }

  async getDiaryByDate(tenant: TenantContext, localDate: string): Promise<DiaryModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diaries)
      .where(
        and(
          eq(diaries.workspaceId, tenant.workspaceId),
          eq(diaries.subjectUserId, tenant.subjectUserId),
          eq(diaries.localDate, localDate),
        ),
      );
    return (found as DiaryModel) ?? null;
  }
}
