import { describe, it, expect, beforeEach } from "vitest";
import {
  createInMemoryDatabase,
  initDatabaseSchema,
  SqliteDiaryRepository,
  type AervoxDatabase,
  type TenantContext,
} from "../src/index.js";
import type { Client } from "@libsql/client";

describe("ADR-011: 日记周期 CAS 乐观锁与条件唯一索引测试", () => {
  let db: AervoxDatabase;
  let client: Client;
  let repo: SqliteDiaryRepository;

  const tenant: TenantContext = {
    workspaceId: "ws_diary_test",
    subjectUserId: "usr_david",
  };

  beforeEach(async () => {
    const res = await createInMemoryDatabase();
    db = res.db;
    client = res.client;
    await initDatabaseSchema(client);
    repo = new SqliteDiaryRepository(db);
  });

  it("Worker 通过 CAS 机制竞争领取 Cycle lease，版本不符者被拒绝", async () => {
    const cycle = await repo.createCycle(tenant, {
      id: "cycle_20260824",
      scheduleEpochId: "epoch_1",
      localDate: "2026-08-24",
      previousCutoffAt: "2026-08-23T22:00:00Z",
      cutoffAt: "2026-08-24T22:00:00Z",
    });
    expect(cycle.scheduleVersion).toBe(1);

    // Worker 1 以版本 1 领取 Cycle
    const claim1 = await repo.claimCycleWithLease(tenant, {
      cycleId: cycle.id,
      workerId: "worker_node_1",
      leaseDurationMs: 60000,
      expectedScheduleVersion: 1,
    });
    expect(claim1.success).toBe(true);
    expect(claim1.newScheduleVersion).toBe(2);

    // Worker 2 依然尝试以旧版本 1 领取 Cycle，应当 CAS 失败
    const claim2 = await repo.claimCycleWithLease(tenant, {
      cycleId: cycle.id,
      workerId: "worker_node_2",
      leaseDurationMs: 60000,
      expectedScheduleVersion: 1,
    });
    expect(claim2.success).toBe(false);
  });

  it("同一本地日期标签下只允许存在一份 auto_generated = 1 的自动日记", async () => {
    const cycle = await repo.createCycle(tenant, {
      id: "cycle_day_1",
      scheduleEpochId: "epoch_1",
      localDate: "2026-08-24",
      previousCutoffAt: "2026-08-23T22:00:00Z",
      cutoffAt: "2026-08-24T22:00:00Z",
    });

    // 发布首份自动日记
    await repo.publishDiaryWithCycle(tenant, {
      cycleId: cycle.id,
      diary: {
        id: "diary_auto_1",
        localDate: "2026-08-24",
        title: "今日学习记录",
        content: "完成了力学与微积分复习。",
        autoGenerated: 1,
      },
      expectedScheduleVersion: 1,
    });

    const published = await repo.getDiaryByDate(tenant, "2026-08-24");
    expect(published).not.toBeNull();
    expect(published!.title).toBe("今日学习记录");

    // 再次尝试插入同日期的自动日记应触发 SQLite 条件唯一索引冲突
    const cycle2 = await repo.createCycle(tenant, {
      id: "cycle_day_2",
      scheduleEpochId: "epoch_1",
      localDate: "2026-08-24",
      previousCutoffAt: "2026-08-23T22:00:00Z",
      cutoffAt: "2026-08-24T22:00:00Z",
    });

    await expect(
      repo.publishDiaryWithCycle(tenant, {
        cycleId: cycle2.id,
        diary: {
          id: "diary_auto_duplicate",
          localDate: "2026-08-24",
          title: "重复的日记",
          content: "内容",
          autoGenerated: 1,
        },
        expectedScheduleVersion: 1,
      }),
    ).rejects.toThrow();
  });
});
