/**
 * Aervox｜思隅 @aervox/database — 仓储接口定义（Repository Interfaces）
 *
 * 规则依据：仓储抽象与 Port 模式，上层业务仅依赖接口，解耦具体 SQLite / PostgreSQL 实现。
 */
import type { TenantContext } from "../tenant.js";

export interface SessionModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface TurnModel {
  id: string;
  sessionId: string;
  workspaceId: string;
  subjectUserId: string;
  idempotencyKey: string;
  status: string;
  lastSequence: number;
  error?: unknown;
  createdAt: string;
  updatedAt: string;
}

export interface MessageVersionModel {
  id: string;
  turnId: string;
  workspaceId: string;
  subjectUserId: string;
  role: string;
  version: number;
  content: string;
  isRedacted: number;
  createdAt: string;
}

export interface TurnStreamEventModel {
  id: string;
  turnId: string;
  workspaceId: string;
  subjectUserId: string;
  sequence: number;
  eventType: string;
  payloadVersion: number;
  data: unknown;
  occurredAt: string;
}

export interface OutboxEventModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  controlEventId?: string | null;
  idempotencyKey: string;
  eventType: string;
  payload: unknown;
  status: string;
  retryCount: number;
  lastError?: string | null;
  createdAt: string;
  publishedAt?: string | null;
}

export interface IConversationRepository {
  createSession(tenant: TenantContext, title: string): Promise<SessionModel>;
  getSession(tenant: TenantContext, sessionId: string): Promise<SessionModel | null>;
  createTurnWithOutbox(
    tenant: TenantContext,
    turn: { id: string; sessionId: string; idempotencyKey: string; status?: string },
    userMessage: { id: string; content: string },
    outboxEvent?: { id: string; eventType: string; idempotencyKey: string; payload: unknown },
  ): Promise<{ turn: TurnModel; message: MessageVersionModel }>;
  getTurn(tenant: TenantContext, turnId: string): Promise<TurnModel | null>;
  getTurnByIdempotencyKey(tenant: TenantContext, idempotencyKey: string): Promise<TurnModel | null>;
  updateTurnStatus(
    tenant: TenantContext,
    turnId: string,
    status: string,
    lastSequence?: number,
    error?: unknown,
  ): Promise<TurnModel | null>;
  appendStreamEvent(
    tenant: TenantContext,
    event: {
      id: string;
      turnId: string;
      sequence: number;
      eventType: string;
      payloadVersion?: number;
      data: unknown;
      occurredAt?: string;
    },
  ): Promise<TurnStreamEventModel>;
  getStreamEvents(
    tenant: TenantContext,
    turnId: string,
    afterSequence?: number,
  ): Promise<TurnStreamEventModel[]>;
  deleteMessage(tenant: TenantContext, messageId: string): Promise<boolean>;
}

export interface MemoryRecordModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  layer: string;
  type: string;
  content: string;
  canonicalParentId?: string | null;
  sourceTurnId?: string | null;
  version: number;
  isDeleted: number;
  createdAt: string;
  updatedAt: string;
}

export interface MemoryEdgeModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  sourceId: string;
  targetId: string;
  relationType: string;
  createdAt: string;
}

export interface MemoryTreeNode {
  record: MemoryRecordModel;
  depth: number;
  path: string;
  children: MemoryTreeNode[];
}

export interface IMemoryRepository {
  createRecord(
    tenant: TenantContext,
    record: {
      id: string;
      layer: string;
      type: string;
      content: string;
      canonicalParentId?: string | null;
      sourceTurnId?: string | null;
    },
  ): Promise<MemoryRecordModel>;
  getRecord(tenant: TenantContext, id: string): Promise<MemoryRecordModel | null>;
  listRecordsByLayer(tenant: TenantContext, layer: string): Promise<MemoryRecordModel[]>;
  createEdge(
    tenant: TenantContext,
    edge: { id: string; sourceId: string; targetId: string; relationType: string },
  ): Promise<MemoryEdgeModel>;
  getTreeProjection(
    tenant: TenantContext,
    rootRecordId?: string | null,
  ): Promise<MemoryTreeNode[]>;
  softDeleteRecord(tenant: TenantContext, id: string): Promise<boolean>;
}

export interface DiaryModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  localDate: string;
  autoGenerated: number;
  title: string;
  content: string;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface DiaryCycleModel {
  id: string;
  workspaceId: string;
  subjectUserId: string;
  scheduleEpochId: string;
  localDate: string;
  previousCutoffAt: string;
  cutoffAt: string;
  status: string;
  scheduleVersion: number;
  fencingToken: number;
  diaryId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface IDiaryRepository {
  createCycle(
    tenant: TenantContext,
    cycle: {
      id: string;
      scheduleEpochId: string;
      localDate: string;
      previousCutoffAt: string;
      cutoffAt: string;
      status?: string;
    },
  ): Promise<DiaryCycleModel>;
  getCycle(tenant: TenantContext, cycleId: string): Promise<DiaryCycleModel | null>;
  claimCycleWithLease(
    tenant: TenantContext,
    params: {
      cycleId: string;
      workerId: string;
      leaseDurationMs: number;
      expectedScheduleVersion: number;
    },
  ): Promise<{ success: boolean; newScheduleVersion?: number; fencingToken?: number }>;
  publishDiaryWithCycle(
    tenant: TenantContext,
    params: {
      cycleId: string;
      diary: { id: string; localDate: string; title: string; content: string; autoGenerated?: number };
      expectedScheduleVersion: number;
      outboxEvent?: { id: string; eventType: string; idempotencyKey: string; payload: unknown };
    },
  ): Promise<{ diary: DiaryModel; cycle: DiaryCycleModel }>;
  getDiaryByDate(tenant: TenantContext, localDate: string): Promise<DiaryModel | null>;
}

export interface IOutboxRepository {
  insertEvent(
    tenant: TenantContext,
    event: {
      id: string;
      idempotencyKey: string;
      eventType: string;
      payload: unknown;
      controlEventId?: string | null;
    },
  ): Promise<OutboxEventModel>;
  fetchPendingEvents(limit?: number): Promise<OutboxEventModel[]>;
  markPublished(eventId: string): Promise<void>;
  markFailed(eventId: string, error: string): Promise<void>;
}
