/**
 * Aervox｜思隅 @aervox/api — DiaryWriteTool 运行时实现（CAP-009 对话触发）
 *
 * 用户在对话中表达「写篇日记给我」时，模型经 aervox_diary_write 工具触发生成。
 * 行为与契约对齐 packages/contracts diaryWriteToolInputSchema/Output。
 *
 * 关键行为：
 * - 当日无日记 → 创建 on-demand 周期并走既有事务发布（publishDiaryWithCycle：日记 + 周期 CAS + outbox）；
 * - 当日已有日记 → 以 rewrite 视角落新版本并推进主行（updateDiaryContent），不覆盖历史版本；
 * - 发布幂等由仓储 CAS 保证；素材窗口 = 当日本地零点至当前时刻。
 */
import type { SqliteDiaryRepository, TenantContext } from "@aervox/database";
import type { DiaryWriteToolInput, DiaryWriteToolOutput } from "@aervox/contracts";
import type { DiaryGenerationService } from "./generation.js";
import { generateDiaryId } from "./generation.js";

export interface DiaryWriteToolDeps {
  diaryRepo: SqliteDiaryRepository;
  generation: DiaryGenerationService;
}

/** 当日本地日期标签（服务器时区；调度路径的 timezoneSnapshot 机制在阶段 2 接入） */
export function localDateToday(now = new Date()): string {
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
}

/** 当日窗口：本地零点（ISO 近似，按本地日期前缀过滤）至当前时刻 */
export function todayWindow(now = new Date()): { startIso: string; endIso: string } {
  const localDate = localDateToday(now);
  return {
    startIso: `${localDate}T00:00:00`,
    endIso: now.toISOString(),
  };
}

export class DiaryWriteTool {
  constructor(private readonly deps: DiaryWriteToolDeps) {}

  async run(tenant: TenantContext, input: DiaryWriteToolInput): Promise<DiaryWriteToolOutput> {
    const { diaryRepo, generation } = this.deps;
    const now = new Date();
    const localDate = localDateToday(now);
    const window = todayWindow(now);

    // 1. 生成草稿（素材采集在服务内；反虚构守则在 Prompt 层）
    const draft = await generation.generate(tenant, {
      localDate,
      window,
      focus: input?.focus,
    });

    // 2. 当日已有日记 → rewrite 版本（历史版本不覆盖，主行推进）
    const existing = await diaryRepo.getDiaryByDate(tenant, localDate);
    if (existing) {
      await diaryRepo.createDiaryVersion(tenant, {
        id: generateDiaryId("dv"),
        diaryId: existing.id,
        perspective: "rewrite",
        content: draft.content,
      });
      const updated = await diaryRepo.updateDiaryContent(tenant, existing.id, {
        title: draft.title,
        content: draft.content,
      });
      return {
        diaryId: updated.id,
        localDate,
        title: draft.title,
        content: draft.content,
        mode: "rewritten",
        materialCount: draft.materialCount,
        generatedBy: draft.generatedBy,
      };
    }

    // 3. 无当日日记 → on-demand 周期 + 事务发布（outbox 事件与 Worker 路径一致）
    const cycle = await diaryRepo.createCycle(tenant, {
      id: generateDiaryId("cyc"),
      scheduleEpochId: `on_demand:${localDate}`,
      localDate,
      previousCutoffAt: window.startIso,
      cutoffAt: window.endIso,
    });
    const published = await diaryRepo.publishDiaryWithCycle(tenant, {
      cycleId: cycle.id,
      diary: {
        id: generateDiaryId("diary"),
        localDate,
        title: draft.title,
        content: draft.content,
        autoGenerated: 1,
      },
      expectedScheduleVersion: 1,
      outboxEvent: {
        id: generateDiaryId("outbox"),
        eventType: "diary.published",
        idempotencyKey: generateDiaryId("idem_diary_ondemand"),
        payload: { cycleId: cycle.id, localDate, trigger: "on_demand" },
      },
    });
    await diaryRepo.createDiaryVersion(tenant, {
      id: generateDiaryId("dv"),
      diaryId: published.diary.id,
      perspective: "ai_generated",
      content: draft.content,
    });

    return {
      diaryId: published.diary.id,
      localDate,
      title: draft.title,
      content: draft.content,
      mode: "created",
      materialCount: draft.materialCount,
      generatedBy: draft.generatedBy,
    };
  }
}
