/**
 * CAP-009 对话触发写日记（aervox_diary_write）集成测试
 *
 * 覆盖：PET-05 审批强制 / 模板生成（scripted 模式）/ 新建与改写发布路径 /
 * 素材采集（当日消息）/ 授权后执行（createRuntimeToolProvider 审批缝）。
 * 规则依据：PRD §6.7（反虚构、当日唯一自动日记、改写不覆盖历史）。
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  createInMemoryDatabase,
  SqliteConversationRepository,
  type AervoxDatabase,
} from "@aervox/database";
import { buildApp } from "../src/app.js";
import { createRuntimeToolProvider } from "../src/modules/conversation/agent-executor.js";
import type { FastifyInstance } from "fastify";

const headers = {
  "x-workspace-id": "ws_cap009",
  "x-user-id": "usr_cap009",
} as const;
const tenant = { workspaceId: "ws_cap009", subjectUserId: "usr_cap009" } as const;

interface DiaryWriteOutput {
  diaryId: string;
  localDate: string;
  title: string;
  content: string;
  mode: "created" | "rewritten";
  materialCount: number;
  generatedBy: "llm" | "template";
}

const todayLocal = (): string => {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

describe("CAP-009 对话触发写日记", () => {
  let app: FastifyInstance;
  let db: AervoxDatabase;
  let built: Awaited<ReturnType<typeof buildApp>>;
  let cleanup: () => Promise<void>;
  let seq = 0;

  beforeEach(async () => {
    // scripted 模式：日记生成服务走确定性模板（无网络依赖），全链路可测
    process.env.AERVOX_LOOP_PROVIDER = "scripted";
    const res = await createInMemoryDatabase();
    db = res.db;
    cleanup = res.cleanup;
    built = await buildApp({ db, client: res.client });
    app = built.app;
    await app.ready();
  });

  afterEach(async () => {
    delete process.env.AERVOX_LOOP_PROVIDER;
    await app.close();
    await cleanup();
  });

  /** 种一条当日聊天消息（走真实 session → turn → message 版本写入路径） */
  const seedMessage = async (content: string): Promise<{ turnId: string }> => {
    const repo = new SqliteConversationRepository(db);
    const session = await repo.createSession(tenant, "CAP-009 素材会话");
    seq += 1;
    const { turn } = await repo.createTurnWithOutbox(
      tenant,
      {
        id: `t_${seq}_${Date.now().toString(36)}`,
        sessionId: session.id,
        idempotencyKey: `idem_${seq}_${Date.now().toString(36)}`,
      },
      { id: `m_${seq}_${Date.now().toString(36)}`, content },
    );
    return { turnId: turn.id };
  };

  it("PET-05：未授权调用被拒绝（write_with_approval fail-closed）", async () => {
    await expect(
      built.toolRuntime.callTool(tenant, "aervox_diary_write", {}, { approval: false }),
    ).rejects.toThrow(/requires approval/);
  });

  it("授权后新建当日日记：模板生成、可经 GET /v1/diaries 查询、素材含当日消息", async () => {
    await seedMessage("今天复习了导数，错了两道题");

    const output = (await built.toolRuntime.callTool(
      tenant,
      "aervox_diary_write",
      {},
      { approval: true },
    )) as DiaryWriteOutput;

    expect(output.mode).toBe("created");
    expect(output.generatedBy).toBe("template");
    expect(output.localDate).toBe(todayLocal());
    expect(output.materialCount).toBeGreaterThan(0);

    const res = await app.inject({
      method: "GET",
      url: `/v1/diaries?localDate=${output.localDate}`,
      headers,
    });
    expect(res.statusCode).toBe(200);
    const diary = res.json() as { id: string; content: string; autoGenerated: number };
    expect(diary.id).toBe(output.diaryId);
    expect(diary.autoGenerated).toBe(1);
    // 模板日记诚实呈现当日对话条数（反虚构：有素材才有内容）
    expect(diary.content).toContain("1 句话");
  });

  it("同日再次触发：改写版本落库、主行推进、不覆盖历史", async () => {
    const first = (await built.toolRuntime.callTool(
      tenant,
      "aervox_diary_write",
      {},
      { approval: true },
    )) as DiaryWriteOutput;
    const second = (await built.toolRuntime.callTool(
      tenant,
      "aervox_diary_write",
      { focus: "重点写错题" },
      { approval: true },
    )) as DiaryWriteOutput;

    expect(second.mode).toBe("rewritten");
    expect(second.diaryId).toBe(first.diaryId);

    const res = await app.inject({
      method: "GET",
      url: `/v1/diaries?localDate=${second.localDate}`,
      headers,
    });
    const diary = res.json() as { version: number; status: string };
    expect(diary.version).toBe(2);
    expect(diary.status).toBe("edited");
  });

  it("无素材当日：生成简短空日记（诚实降级，不虚构）", async () => {
    const output = (await built.toolRuntime.callTool(
      tenant,
      "aervox_diary_write",
      {},
      { approval: true },
    )) as DiaryWriteOutput;
    expect(output.mode).toBe("created");
    expect(output.materialCount).toBe(0);
    expect(output.content).toContain("还没怎么说话");
  });

  it("审批缝：createRuntimeToolProvider 未授权返回 needsApproval，授权后执行成功", async () => {
    const repo = new SqliteConversationRepository(db);
    // 真实 turn 落库（审批表有 turn 外键）
    const { turnId } = await seedMessage("帮我写今天的日记");
    const provider = createRuntimeToolProvider(built.toolRuntime, tenant, { conversationRepo: repo });
    const executionInput = {
      turnId,
      attemptId: "at_cap009_1",
      invocationId: "inv_cap009_1",
      name: "aervox_diary_write",
      arguments: {},
    };

    // 1. 首次执行：无授权 → needsApproval（循环据此中断等待用户）
    const first = await provider.execute(executionInput);
    expect(first.ok).toBe(false);
    expect(first.needsApproval?.toolName).toBe("aervox_diary_write");

    // 2. 用户批准（granted）后同参数执行 → 工具真正运行
    const approval = await repo.recordToolApproval(tenant, {
      turnId,
      attemptId: executionInput.attemptId,
      toolName: "aervox_diary_write",
      argumentsHash: "{}",
      requester: tenant.subjectUserId,
      state: "granted",
      toolVersion: null,
    });
    expect(approval.state).toBe("granted");

    const second = await provider.execute(executionInput);
    expect(second.ok).toBe(true);
    expect((second.output as DiaryWriteOutput).mode).toBe("created");
  });
});
